import React from 'react'

const table = () => {
    return (
        <div>
            <div className='table-section'>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Name</th>
                            <th>Name</th>
                            <th>Name</th>
                            <th>Name</th>
                            <th>Name</th>
                            <th>Name</th>
                            <th>Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr><tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr><tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr><tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr><tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr><tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr><tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr><tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                        <tr>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                            <td>Swarnali</td>
                        </tr>
                    </tbody>
                </table>
            </div >
        </div>
    )
}

export default table